---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: spire-server
  labels:
    app.kubernetes.io/part-of: nginx-service-mesh
imagePullSecrets:
- name: {{ include "registry-key-name" . }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: spire-server.security.builtin.nsm.nginx
  labels:
    app.kubernetes.io/part-of: nginx-service-mesh
rules:
- apiGroups: [""]
  resources: ["pods", "nodes"]
  verbs: ["get"]
- apiGroups: [""]
  resources: ["configmaps"]
  resourceNames: ["spire-bundle"]
  verbs: ["get", "patch"]
- apiGroups: ["authentication.k8s.io"]
  resources: ["tokenreviews"]
  verbs: ["create"]
- apiGroups: ["apiregistration.k8s.io"]
  resources: ["apiservices"]
  verbs: ["get", "list", "patch", "watch"]
- apiGroups: ["admissionregistration.k8s.io"]
  resources: ["mutatingwebhookconfigurations", "validatingwebhookconfigurations"]
  verbs: ["get", "list", "patch", "watch"]
{{- if .Values.mtls.upstreamAuthority.certManager }}
- apiGroups: ["cert-manager.io"]
  resources: ["certificaterequests"]
  verbs: ["get", "list", "create", "delete"]
{{- end }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: spire-server.security.builtin.nsm.nginx
  labels:
    app.kubernetes.io/part-of: nginx-service-mesh
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: spire-server.security.builtin.nsm.nginx
subjects:
- kind: ServiceAccount
  name: spire-server
  namespace: {{ .Release.Namespace }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: spire-controller-manager.security.builtin.nsm.nginx
  labels:
    app.kubernetes.io/part-of: nginx-service-mesh
rules:
- apiGroups: [""]
  resources: ["pods", "namespaces", "nodes"]
  verbs: ["get", "list", "watch"]
- apiGroups: ["admissionregistration.k8s.io"]
  resources: ["validatingwebhookconfigurations"]
  verbs: ["get", "list", "patch", "watch"]
- apiGroups: ["spire.spiffe.io"]
  resources: ["clusterfederatedtrustdomains"]
  verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
- apiGroups: ["spire.spiffe.io"]
  resources: ["clusterfederatedtrustdomains/finalizers"]
  verbs: ["update"]
- apiGroups: ["spire.spiffe.io"]
  resources: ["clusterfederatedtrustdomains/status"]
  verbs: ["get", "patch", "update"]
- apiGroups: ["spire.spiffe.io"]
  resources: ["clusterspiffeids"]
  verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
- apiGroups: ["spire.spiffe.io"]
  resources: ["clusterspiffeids/finalizers"]
  verbs: ["update"]
- apiGroups: ["spire.spiffe.io"]
  resources: ["clusterspiffeids/status"]
  verbs: ["get", "patch", "update"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: spire-controller-manager.security.builtin.nsm.nginx
  labels:
    app.kubernetes.io/part-of: nginx-service-mesh
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: spire-controller-manager.security.builtin.nsm.nginx
subjects:
- kind: ServiceAccount
  name: spire-server
  namespace: {{ .Release.Namespace }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: spire-leader-election
  labels:
    app.kubernetes.io/part-of: nginx-service-mesh
rules:
  - apiGroups: [""]
    resources: ["configmaps"]
    verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
  - apiGroups: ["coordination.k8s.io"]
    resources: ["leases"]
    verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
  - apiGroups: [""]
    resources: ["events"]
    verbs: ["create", "patch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: spire-leader-election
  labels:
    app.kubernetes.io/part-of: nginx-service-mesh
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: spire-leader-election
subjects:
- kind: ServiceAccount
  name: spire-server
  namespace: {{ .Release.Namespace }}
{{- if (or (include "ua-secret-name" .) (include "ua-vault-env-name" .)) }}
---
apiVersion: v1
kind: Secret
metadata:
  name: spire-server
  labels:
    app.kubernetes.io/part-of: nginx-service-mesh
type: Opaque
data:
  {{- if (include "ua-secret-name" .) }}
  {{ include "ua-secret-name" . }}: {{ include "ua-secret-value" . }}{{ end }}
  {{- if (include "ua-vault-env-name" .) }}
  {{ include "ua-vault-env-name" . }}: {{ include "ua-vault-env-value" . }}{{ end }}
{{- end }}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: spire-bundle
  labels:
    app.kubernetes.io/part-of: nginx-service-mesh
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: spire-server
  labels:
    app.kubernetes.io/part-of: nginx-service-mesh
data:
  server.conf: {{ tpl (.Files.Get "configs/spire-server.conf") . | quote }}
  {{ if (include "ua-upstream-cert" .) -}}
  {{ include "ua-upstream-cert" . }}{{ end }}
  {{ if (include "ua-upstream-client-cert" .) -}}
  {{ include "ua-upstream-client-cert" . }}{{ end }}
  {{ if (include "ua-upstream-bundle" .) -}}
  {{ include "ua-upstream-bundle" . }}{{ end }}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: spire-controller-manager-config
  labels:
    app.kubernetes.io/part-of: nginx-service-mesh
data:
  spire-controller-manager-config.yaml: |
    apiVersion: spire.spiffe.io/v1alpha1
    kind: ControllerManagerConfig
    metrics:
      bindAddress: 127.0.0.1:8082
    healthProbe:
      bindAddress: 127.0.0.1:8083
    leaderElection:
      leaderElect: true
      resourceName: {{ .Release.Name | sha256sum | trunc 8 }}.spiffe.io
      resourceNamespace: {{ .Release.Namespace }}
    clusterName: nginx-mesh
    trustDomain: {{ .Values.mtls.trustDomain }}
    spireServerSocketPath: /run/spire/sockets/spire-registration.sock
    validatingWebhookConfigurationName: spire-controller-manager.security.builtin.nsm.nginx
    ignoreNamespaces:
    - kube-system
---
apiVersion: spire.spiffe.io/v1alpha1
kind: ClusterSPIFFEID
metadata:
  name: spire-controller-manager.security.builtin.nsm.nginx
  labels:
    app.kubernetes.io/part-of: nginx-service-mesh
spec:
  spiffeIDTemplate: "spiffe://{{`{{ .TrustDomain }}`}}/ns/{{`{{ .PodMeta.Namespace }}`}}/sa/{{`{{ .PodSpec.ServiceAccountName }}`}}"
  podSelector:
    matchLabels:
      spiffe.io/spiffeid: "true"
  dnsNameTemplates:
  - "{{`{{ .PodMeta.Name}}`}}"
  #- "{{`{{ .PodSpec.ServiceAccountName }}`}}.{{`{{ .PodMeta.Namespace }}`}}.svc"
  #- "{{`{{ index .PodMeta.Labels \"app\" }}`}}.{{`{{ .PodMeta.Namespace }}`}}.svc"
  - "{{`{{ index .PodMeta.Labels \"app.kubernetes.io/name\" }}`}}.{{`{{ .PodMeta.Namespace }}`}}.svc"
  # This doesn't add svc name to dns names...may need to open an issue if this is needed
---
apiVersion: v1
kind: Service
metadata:
  name: spire-server
  labels:
    app.kubernetes.io/name: spire-server
    app.kubernetes.io/part-of: nginx-service-mesh
spec:
  ports:
  - name: api
    protocol: TCP
    port: 8081
    targetPort: 8081
  selector:
    app.kubernetes.io/name: spire-server
    app.kubernetes.io/part-of: nginx-service-mesh
---
apiVersion: v1
kind: Service
metadata:
  name: spire-server-bundle-endpoint
  labels:
    app.kubernetes.io/name: spire-server
    app.kubernetes.io/part-of: nginx-service-mesh
spec:
  type: ClusterIP
  ports:
  - name: api
    port: 8443
    protocol: TCP
  selector:
    app.kubernetes.io/name: spire-server
    app.kubernetes.io/part-of: nginx-service-mesh
---
apiVersion: v1
kind: Service
metadata:
  name: spire-controller-manager-webhook-service
  labels:
    app.kubernetes.io/name: spire-server
    app.kubernetes.io/part-of: nginx-service-mesh
spec:
  ports:
  - port: 443
    protocol: TCP
    targetPort: 9443
  selector:
    app.kubernetes.io/name: spire-server
    app.kubernetes.io/part-of: nginx-service-mesh
---
apiVersion: admissionregistration.k8s.io/v1
kind: ValidatingWebhookConfiguration
metadata:
  name: spire-controller-manager.security.builtin.nsm.nginx
  labels:
    app.kubernetes.io/part-of: nginx-service-mesh
    spiffe.io/webhook: "true"
webhooks:
- admissionReviewVersions: ["v1"]
  clientConfig:
    service:
      name: spire-controller-manager-webhook-service
      namespace: {{ .Release.Namespace }}
      path: /validate-spire-spiffe-io-v1alpha1-clusterfederatedtrustdomain
  name: vclusterfederatedtrustdomain.kb.io
  rules:
  - apiGroups: ["spire.spiffe.io"]
    apiVersions: ["v1alpha1"]
    operations: ["CREATE", "UPDATE"]
    resources: ["clusterfederatedtrustdomains"]
  sideEffects: None
- admissionReviewVersions: ["v1"]
  clientConfig:
    service:
      name: spire-controller-manager-webhook-service
      namespace: {{ .Release.Namespace }}
      path: /validate-spire-spiffe-io-v1alpha1-clusterspiffeid
  name: vclusterspiffeid.kb.io
  rules:
  - apiGroups: ["spire.spiffe.io"]
    apiVersions: ["v1alpha1"]
    operations: ["CREATE", "UPDATE"]
    resources: ["clusterspiffeids"]
  sideEffects: None
---
apiVersion: apps/v1
{{- if eq .Values.mtls.persistentStorage "on" }}
kind: StatefulSet
{{- else }}
kind: Deployment
{{- end }}
metadata:
  name: spire-server
  labels:
    app.kubernetes.io/name: spire-server
    app.kubernetes.io/part-of: nginx-service-mesh
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: spire-server
      app.kubernetes.io/part-of: nginx-service-mesh
  {{- if eq .Values.mtls.persistentStorage "on" }}
  serviceName: spire-server
  {{- end }}
  template:
    metadata:
      labels:
        app.kubernetes.io/name: spire-server
        app.kubernetes.io/part-of: nginx-service-mesh
    spec:
      serviceAccountName: spire-server
      shareProcessNamespace: true
      containers:
      - name: spire-server
        image: {{ include "spire.image-server" . }}/spire-server:1.5.4
        imagePullPolicy: {{ .Values.registry.imagePullPolicy }}
        args:
        - -config
        - /run/spire/config/server.conf
        ports:
        - name: spire-server
          protocol: TCP
          containerPort: 8081
        {{- if (include "ua-vault-env-name" .) }}
        env:
        - name: {{ include "ua-vault-env-name" . }}
          valueFrom:
            secretKeyRef:
              name: spire-server
              key: {{ include "ua-vault-env-name" . }}
        {{- end }}
        volumeMounts:
        - name: spire-config
          mountPath: /run/spire/config
          readOnly: true
        {{- if (include "ua-secret-mountpath" .) }}
        - name: spire-secrets
          mountPath: {{ include "ua-secret-mountpath" . }}
          readOnly: true
        {{- end }}
        - name: spire-data
          mountPath: /run/spire/data
          readOnly: false
        - name: spire-server-socket
          mountPath: /run/spire/sockets
          readOnly: false
        livenessProbe:
          httpGet:
            path: /live
            port: 8080
          failureThreshold: 2
          initialDelaySeconds: 15
          periodSeconds: 60
          timeoutSeconds: 3
        readinessProbe:
          httpGet:
            path: /ready
            port: 8080
          initialDelaySeconds: 5
          periodSeconds: 5
      - name: spire-controller-manager
        image: {{ include "spiffe.image-server" . }}/spire-controller-manager:0.2.1
        imagePullPolicy: {{ .Values.registry.imagePullPolicy }}
        ports:
        - containerPort: 9443
        args:
        - --config=spire-controller-manager-config.yaml
        volumeMounts:
        - name: spire-server-socket
          mountPath: /run/spire/sockets
          readOnly: true
        - name: spire-controller-manager-config
          mountPath: /spire-controller-manager-config.yaml
          subPath: spire-controller-manager-config.yaml
      volumes:
      - name: spire-config
        configMap:
          name: spire-server
      {{- if (include "ua-secret-name" .) }}
      - name: spire-secrets
        secret:
          secretName: spire-server
          items:
          - key: {{ include "ua-secret-name" . }}
            path: {{ include "ua-secret-name" . }}
      {{- end }}
      - name: spire-server-socket
        emptyDir: {}
      - name: spire-controller-manager-config
        configMap:
          name: spire-controller-manager-config
      {{- if eq .Values.mtls.persistentStorage "off" }}
      - name: spire-data
        emptyDir: {}
      {{- end }}
  {{- if eq .Values.mtls.persistentStorage "on" }}
  volumeClaimTemplates:
  - metadata:
      name: spire-data
      namespace: {{ .Release.Namespace }}
    spec:
      accessModes:
      - ReadWriteOnce
      resources:
        requests:
          storage: 1Gi
  {{- end }}
{{- if eq .Values.environment "openshift" }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: system:openshift:scc:nginx-mesh-spire-server-permissions
  labels:
    app.kubernetes.io/part-of: nginx-service-mesh
rules:
- apiGroups: ["security.openshift.io"]
  resources: ["securitycontextconstraints"]
  resourceNames: ["nginx-mesh-spire-server-permissions"]
  verbs: ["use"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: system:openshift:scc:nginx-mesh-spire-server-permissions
  labels:
    app.kubernetes.io/part-of: nginx-service-mesh
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: system:openshift:scc:nginx-mesh-spire-server-permissions
subjects:
- kind: ServiceAccount
  name: spire-server
  namespace: {{ .Release.Namespace }}
---
apiVersion: security.openshift.io/v1
kind: SecurityContextConstraints
metadata:
  name: nginx-mesh-spire-server-permissions
  labels:
    app.kubernetes.io/part-of: nginx-service-mesh
allowHostDirVolumePlugin: false
allowHostIPC: false
allowHostNetwork: false
allowHostPID: false
allowHostPorts: false
allowPrivilegedContainer: false
seLinuxContext:
  type: MustRunAs
readOnlyRootFilesystem: false
runAsUser:
  type: RunAsAny
volumes:
- configMap
- secret
- emptyDir
- persistentVolumeClaim
{{- end }}
